### ISSUE TITLE
Needs positions for the new example images?

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#190]
```css/common.styl``` needs positions for the new example images, I think - not sure if these are manually or automatically generated. See pull request https://github.com/zooniverse/Galaxy-Zoo/pull/187

**Comment by murraycu** [comment]
Yes, either goods_full.coffee
( https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/lib/goods_full_tree.coffee )
has incorrect "examples:" values, or the images (and their mentions in the .styl/css file)
( https://github.com/zooniverse/Galaxy-Zoo/blob/master/css/common.styl#L369 )
are missing. I guess that the "examples:" values are just wrong.

These images are not mentioned in the css file (generated from the .styl file) at all, though the decision tree's examples_count implies that they should exist. For instance, "goods_full-3_a-3_1" is for question 3 ("How many clumps are there"), answer 3 ("clump_4"), example 1 (the 2nd one).

goods_full-3_a-3_0
goods_full-3_a-3_1
goods_full-3_a-4_0
goods_full-3_a-4_1
goods_full-3_a-4_2

goods_full-4_a-3_0
goods_full-4_a-3_1

goods_full-14_a-3_0
goods_full-14_a-3_1
goods_full-14_a-4_0
goods_full-14_a-4_1

goods_full-18_a-0_0
goods_full-18_a-0_1
goods_full-18_x-0_0
goods_full-18_x-0_1
goods_full-18_x-1_0
goods_full-18_x-1_1
goods_full-18_x-2_0
goods_full-18_x-2_1
goods_full-18_x-3_0
goods_full-18_x-3_1
goods_full-18_x-4_0
goods_full-18_x-4_1
goods_full-18_x-5_0
goods_full-18_x-5_1
goods_full-18_x-6_0
goods_full-18_x-6_1
goods_full-18_x-6_2

And these files are mentioned in the .css/.styl file, but they don't exist on the server:
http://static.zooniverse.org/www.galaxyzoo.org/images/examples/goods_full-15_a-0_1.jpg
http://static.zooniverse.org/www.galaxyzoo.org/images/examples/goods_full-13_a-0_1.jpg
http://static.zooniverse.org/www.galaxyzoo.org/images/examples/goods_full-8_a-1_1.jpg
http://static.zooniverse.org/www.galaxyzoo.org/images/examples/goods_full-10_a-1_1.jpg

The web pages are trying to show these last few images which then appear as empty squares but luckily it's hard to see that the square is even there.

**Comment by murraycu** [comment]
My merge request (see above) adds entries for most files - because most exist in public/images/examples/. I very much doubt that this file is generated, though maybe it should be.

It's not quite all the missing images. I also notice that goods_full-18 ("What are the odd features?") has much fewer examples than the equivalent question (sloan-6) in the sloan tree, used previously. Is this intentional?

**Comment by willettk** [comment]
Not intentional by explicit design, but more due to the fact that it was harder to find reliable examples of those "rare" categories in past GOODS imaging. 

If merge https://github.com/zooniverse/Galaxy-Zoo/pull/192 looks acceptable to you, @chrissnyder, it'd be useful to deploy so that users can continue with the mobile app.

**Comment by willettk** [comment]
Also - we have even more sets of images in the coming months. Are there changes we need to make in advance to make sure new images will work with the mobile app?

**Comment by chrissnyder** [comment]
I scripted up creation of the CSS for the examples, but clearly I had a bug in there somewhere. Thanks for the corrections.

It's worth mentioning that I heard people speak of moving Galaxy Zoo to Panoptes in the coming months. I don't know what that means for the current site (if we'll be keeping it and just swapping out the API, or doing something more major), but until there is a better idea of what is going on, I don't think it would an effective use of time to add more groups into the current system.

**Comment by willettk** [comment]
Very fair. I'll ask specifically about GZ/Panoptes when I'm in Oxford next
week.

**Comment by murraycu** [comment]
OK, so assuming that the list of example images in public/images/examples/ is what's correct then merge #193 should be the last correction necessary to make the examples counts in the decision tree correct.

> it'd be useful to deploy so that users can continue with the mobile app. 

These corrections are not just for the app - they are necessary so that users of the regular web UI see the example images and don't see odd effects (such as repeated wrong images as placeholders, for some reason). However, for boring technical reasons it would be helpful for me if it was deployed - my code grabs the icons from the server rather than from the github checkout.

Is there any particular reason that you are using the full images as the icons instead of smaller 100x100 versions, such as the ones that were put in the one examples.jpg file for the sloan tree?
https://github.com/zooniverse/Galaxy-Zoo/blob/master/public/images/examples.jpg
(Or is it just that nobody can remember how that file was created?)

**Comment by murraycu** [comment]
> Also - we have even more sets of images in the coming months. Are there changes we need to 
> make in advance to make sure new images will work with the mobile app?

Just let me know and I'll take care of it. For each new set/group/survey I generally have to:
- discover the group ID.
- get the new decision tree (CoffeeScript code in app/lib/*_tree.coffee, which I convert into an XML file),
  using my eccentric branch of GalaxyZoo.
- get the new answer icons and example icons, by enabling some java code in my android app which parses the CSS file to discover what images to use. I should really do tihs in CoffeeScript or javascript instead, but I'm lazy.

**Comment by murraycu** [comment]
By the way, the new questions aren't being translated:
https://github.com/zooniverse/Translator/issues/11
I guess someone needs to trigger something somewhere.

**Comment by murraycu** [comment]
It would be nice if this could be merged:
https://github.com/zooniverse/Galaxy-Zoo/pull/193

I've already made the changes in the Android app.

**Comment by willettk** [comment]
I know @bumishness is out of town for a few more days, and I don't feel
comfortable authorizing merges myself. Hopefully it can be done when he
gets back, or by @edpaget if that's possible.

**Comment by murraycu** [comment]
I've added some documentation for the (rather hacky) things that I would do when changing the active surveys next time, in case anyone else ever needs to do it:
https://github.com/murraycu/android-galaxyzoo/blob/master/README_changing_surveys.md

**Comment by chrissnyder** [comment]
Merged.
