### ISSUE TITLE
SkyServer link for newly-added Hubble galaxies

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Galaxy-Zoo#194]
The newly added Hubble galaxies won't all be in SkyServer, but some of them will, so could we change the link to SkyServer on Examine from the id-based linking that's there now? 

Using Zooniverse ID AGZ00080AE as an example, it would go from:
http://cas.sdss.org/dr7/en/tools/quicklook/quickobj.asp?id=

to a position-based link (also searching the newer data release):
http://skyserver.sdss.org/dr8/en/tools/explore/obj.asp?ra=189.2563136&dec=62.3119392

It would still throw an error for anything that isn't covered, but many of the sources would show up and it would make the volunteers happy to not have to do this search by hand.

**Comment by murraycu** [comment]
At the moment, I'm seeing "View on SkyServer" links with no ID at all in the URL, after an Android app user complained about it. If there can be no working link, shouldn't the link just be removed, rather than being confusingly useless? For instance:
http://www.galaxyzoo.org/#/examine/AGZ0007y34
which just has this URL for its link:
http://cas.sdss.org/dr7/en/tools/quicklook/quickobj.asp?id=

**Comment by murraycu** [comment]
This can be closed now that pull request #196 has fixed it.
