### ISSUE TITLE
Reactivate regular sloan images ASAP

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#203]
Galaxy Zoo has less than 400 active subjects as of late 22 Jun 2015. I think that's going to be done in less than a day, so I'm worried about the site being empty. Can we temporarily reactivate the frequency of `sloan` images so that GZ doesn't run out?

I think this was originally set by https://github.com/zooniverse/Galaxy-Zoo/commit/1e775e0b2d5bf593e429a81d622a418706140165 and @parrish.

**Comment by murraycu** [comment]
Should I update the Android app to do this too, or is this just temporary?

**Comment by willettk** [comment]
Temporary, but hopefully on the timescale of a week or so.

I looked at the app and it seemed to be correctly generating the SDSS color
images; do you need to update anything?

**Comment by murraycu** [comment]
The commit to the web client makes it use mostly the sloan survey, and sometimes the sloan_singleband survey, instead of just the sloan_singleband survey: https://github.com/zooniverse/Galaxy-Zoo/commit/ea8bfd726d3eff1f5fa4d960a7b6727c001d5e90

If the color images are only in the sloan survey and not in the sloan_singleband survey, I don't see how the Android app could be showing any color images, as the Android app uses only the sloan_singleband survey at the moment.

**Comment by willettk** [comment]
Not sure of what might be going on in the backend, but it's definitely delivering color images on my phone. 

![screenshot_2015-06-23-11-36-00](https://cloud.githubusercontent.com/assets/2285931/8304329/cbfac414-199c-11e5-9e9e-17c0803caccd.png)

**Comment by murraycu** [comment]
Maybe you've just got cached images from way back when the Android app uses the sloan survey. To thoroughly test it you could uninstall and reinstall it, or just delete its data and cache via Apps settings.

**Comment by willettk** [comment]
Cleared the cache and now it's back to B/W images, so that explains why.

We'll update you as soon as we have the parameters for the new sets of
images, @murraycu.
